backend:
  name: github
  repo: 4ndymcfly/4ndymcfly.github.io
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"
# publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"  # Carpeta para posts en formato Markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Formato de slug
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Comments", name: "comments", widget: "boolean", default: true }
      - { label: "Table of Contents", name: "toc", widget: "boolean", default: true }

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
