backend:
  name: github
  repo: 4ndymcfly/4ndymcfly.github.io
  branch: main

media_folder: "static/assets/img"
public_folder: "/assets/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Formato de slug
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - label: "Header Image"
        name: "header_image"
        widget: "image"
        media_folder: "static/assets/img/cabeceras"
        public_folder: "/assets/img/cabeceras"
      - label: "Body"
        name: "body"
        widget: "markdown"
        media_folder: "static/assets/img/{{slug}}"
        public_folder: "/assets/img/{{slug}}"
        - { label: "Comments", name: "comments", widget: "boolean", default: true }
      - { label: "Table of Contents", name: "toc", widget: "boolean", default: true }

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

