backend:
  name: git-gateway
  repo: 4ndymcfly/4ndymcfly.github.io
  branch: main  # Reemplaza con la rama que estás utilizando

media_folder: "assets/img"  # Carpeta donde se almacenarán todas las imágenes
public_folder: "/assets/img"  # Ruta pública para acceder a las imágenes

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"  # Carpeta donde se encuentran los posts en formato markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Formato del slug para los posts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }  # Imagen de cabecera
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Comments", name: "comments", widget: "boolean", default: true }  # Para habilitar comentarios
      - { label: "Table of Contents", name: "toc", widget: "boolean", default: true }  # Para habilitar TOC

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      comments: true  # Habilitar comentarios por defecto
      toc: true  # Habilitar TOC por defecto
      permalink: /posts/:title/
